app = "tag-ai-company-research-agent"
primary_region = "dfw"  # Choose a region closest to your users

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1  # Keep at least one instance running
  processes = ["app"]

[env]
  PORT = "8000"

# Add these to have persistent storage for generated reports
[mounts]
  source = "pdf_data"
  destination = "/app/pdfs"

# Add custom health check to ensure app is responsive
[http_service.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20

[checks]
  [checks.http]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/"
    port = 8000
    timeout = "10s"
    type = "http" 